INSERT INTO tb_user(email) VALUES ('maria@gmail.com');
INSERT INTO tb_user(email) VALUES ('joao@gmail.com');
INSERT INTO tb_user(email) VALUES ('ana@gmail.com');
INSERT INTO tb_user(email) VALUES ('lucia@gmail.com');
INSERT INTO tb_user(email) VALUES ('joaquim@gmail.com');

INSERT INTO tb_movie(score, count, title, image) VALUES (4.5, 2,'Capitão América: O Primeiro Vingador', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/yFuKvT4Vm3sKHdFY4eG6I4ldAnn.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (3.3, 3,'Capitã Marvel', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/w2PMyoyLU22YvrGK3smVM9fW1jj.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem de Ferro', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cyecB7godJ6kNHGONFjUyVN9OX5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'O Incrivel Hulk', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/jPu8yiadqgzwFPGKJmGo637ASVP.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem de Ferro 2', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7lmBufEG7P7Y1HClYK3gCxYrkgS.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Thor', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cDJ61O1STtbWNBwefuqVrRe3d7l.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Os Vingadores', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/nNmJRkg8wWnRmzQDe2FwKbPIsJV.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem de Ferro 3', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/aFTYFqrWp4RS46Twm87l5e0ItYb.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Thor: O Mundo Sombrio', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/uhYoytlNaq46dG81wLmHqaSuzWu.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Capitão América 2: O Soldado Invernal', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/aZBZtLCM90QHDCuZFR6oc4NXCWu.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Guardiões da Galáxia', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/ko4N6wWp0UYlMmsVyfIfLyRAZtP.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Guardiões da Galáxia Vol.2', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/aJn9XeesqsrSLKcHfHP4u5985hn.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vingadores: Era do Ultron', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/wjklF1KOHUcKezUjjyAnG5Hi6bK.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem Formiga', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/a7sAqMKv5tkAdMzFfIhPqIBmQ9g.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Capitão América: Guerra Civil', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7FWlcZq3r6525LWOcvO9kNWurN1.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Viúva Negra', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/keIxh0wPr2Ymj0Btjh4gW7JJ89e.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem Aranha: De Volta ao Lar', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/tTlAA0REGPXSZPBfWyTW9ipIv1I.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Doutor Estranho', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eQN31P4IEhyp6NkdccvppJnyuJ4.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Pantera Negra', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/b6ZJZHUdMEFECvGiDpJjlfUWela.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Thor: Ragnarok', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/kaIfm5ryEOwYg8mLbq8HkPuM1Fo.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem Formiga e a Vespa', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/6P3c80EOm7BodndGBUAJHHsHKrp.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vingadores: Guerra Infinita', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/lmZFxXgJE3vgrciwuDib0N8CfQo.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Vingadores: Ultimato', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'WandaVison', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/1i1N0AVRb54H6ZFPDTwbo9MLxSF.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Falcão e o Soldado Invernal', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/eO8h4fwdjWodPr3awVr5wqMN3Ut.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem Aranha: Longe de Casa', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/ng6SSB3JhbcpKTwbPDsRwUYK8Cq.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Homem Aranha: Sem Volta para Casa', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Eternos', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/k2twTjSddgLc1oFFHVibfxp2kQV.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Shang-Chi e a Lenda dos Dez Anéis', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/cinER0ESG0eJ49kXlExM0MEWGxW.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Gavião Arqueiro', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/1R68vl3d5s86JsS2NPjl8UoMqIS.jpg');
INSERT INTO tb_movie(score, count, title, image) VALUES (0, 0, 'Loki', 'https://www.themoviedb.org/t/p/w533_and_h300_bestv2/bZGAX8oMDm3Mo5i0ZPKh9G2OcaO.jpg');

INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 1, 5.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (1, 2, 4.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 1, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 2, 3.0);
INSERT INTO tb_score(movie_id, user_id, value) VALUES (2, 3, 4.0);